[package]
name = "engine-core"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30", features = ["wayland"] }
glutin = "0.32"
glutin-winit = "0.5.0"
glow = "0.17"
engine-renderer = { path = "../engine-renderer" }
engine-input = { version = "0.1.0", path = "../engine-input" }
engine-ecs = { version = "0.1.0", path = "../engine-ecs" }
engine-math = { version = "0.1.0", path = "../engine-math" }
engine-audio = { version = "0.1.0", path = "../engine-audio" }
